export const listdata = [
  {
    id: 1,
    title: "Gateway of India",
    img: "https://kaldanhotels.com/images/kaldan/hotels-in-ecr-chennai.jpg",
    address: "Apollo Bandar, Colaba, Mumbai, Maharashtra 400001, India",
    latitude: 18.921984,
    longitude: 72.834654,
    type: "sightseeing",
    operating_hours: "24 hours",
    price_for_two: "Free",
    contact_info: {
      phone: "+91 22 1234 5678",
      email: "info@gatewayofindia.com",
      website: "http://www.gatewayofindia.com",
    },
  },
  {
    id: 2,
    title: "Taj Mahal",
    img: "https://kaldanhotels.com/images/kaldan/hotels-in-ecr-chennai.jpg",
    address:
      "Dharmapuri, Forest Colony, Tajganj, Agra, Uttar Pradesh 282001, India",
    latitude: 27.1751448,
    longitude: 78.0421422,
    type: "sightseeing",
    operating_hours: "6:00 AM - 6:30 PM (closed on Fridays)",
    price_for_two: "INR 50 for Indians, INR 1100 for Foreigners",
    contact_info: {
      phone: "+91 562 123 4567",
      email: "info@tajmahal.com",
      website: "http://www.tajmahal.com",
    },
  },
  {
    id: 3,
    title: "India Gate",
    img: "https://kaldanhotels.com/images/kaldan/hotels-in-ecr-chennai.jpg",
    address: "Rajpath, India Gate, New Delhi, Delhi 110001, India",
    latitude: 28.612912,
    longitude: 77.2295097,
    type: "sightseeing",
    operating_hours: "24 hours",
    price_for_two: "Free",
    contact_info: {
      phone: "+91 11 1234 5678",
      email: "info@indiagate.com",
      website: "http://www.indiagate.com",
    },
  },
  {
    id: 4,
    title: "Qutub Minar",
    img: "https://kaldanhotels.com/images/kaldan/hotels-in-ecr-chennai.jpg",
    address: "Seth Sarai, Mehrauli, New Delhi, Delhi 110030, India",
    latitude: 28.5244284,
    longitude: 77.1854559,
    type: "sightseeing",
    operating_hours: "7:00 AM - 5:00 PM",
    price_for_two: "INR 60 for Indians, INR 600 for Foreigners",
    contact_info: {
      phone: "+91 11 1234 5679",
      email: "info@qutubminar.com",
      website: "http://www.qutubminar.com",
    },
  },
  {
    id: 5,
    title: "Hawa Mahal",
    img: "https://kaldanhotels.com/images/kaldan/hotels-in-ecr-chennai.jpg",
    address:
      "Hawa Mahal Rd, Badi Choupad, J.D.A. Market, Pink City, Jaipur, Rajasthan 302002, India",
    latitude: 26.923936,
    longitude: 75.826744,
    type: "sightseeing",
    operating_hours: "9:00 AM - 4:30 PM",
    price_for_two: "INR 50 for Indians, INR 200 for Foreigners",
    contact_info: {
      phone: "+91 141 1234 5678",
      email: "info@hawamahal.com",
      website: "http://www.hawamahal.com",
    },
  },
  {
    id: 6,
    title: "Marina Beach",
    img: "https://kaldanhotels.com/images/kaldan/hotels-in-ecr-chennai.jpg",
    address: "Chennai, Tamil Nadu 600004, India",
    latitude: 13.050004,
    longitude: 80.282881,
    type: "activity",
    operating_hours: "24 hours",
    price_for_two: "Free",
    contact_info: {
      phone: "+91 44 1234 5678",
      email: "info@marinabeach.com",
      website: "http://www.marinabeach.com",
    },
  },
  {
    id: 7,
    title: "Charminar",
    img: "https://kaldanhotels.com/images/kaldan/hotels-in-ecr-chennai.jpg",
    address: "Char Kaman, Ghansi Bazaar, Hyderabad, Telangana 500002, India",
    latitude: 17.361563,
    longitude: 78.474665,
    type: "sightseeing",
    operating_hours: "9:30 AM - 5:30 PM",
    price_for_two: "INR 20 for Indians, INR 300 for Foreigners",
    contact_info: {
      phone: "+91 40 1234 5678",
      email: "info@charminar.com",
      website: "http://www.charminar.com",
    },
  },
  {
    id: 8,
    title: "Mysore Palace",
    img: "https://kaldanhotels.com/images/kaldan/hotels-in-ecr-chennai.jpg",
    address:
      "Sayyaji Rao Rd, Agrahara, Chamrajpura, Mysuru, Karnataka 570001, India",
    latitude: 12.3051635,
    longitude: 76.6552092,
    type: "sightseeing",
    operating_hours: "10:00 AM - 5:30 PM",
    price_for_two: "INR 140 for Indians, INR 1000 for Foreigners",
    contact_info: {
      phone: "+91 821 1234 5678",
      email: "info@mysorepalace.com",
      website: "http://www.mysorepalace.com",
    },
  },
  {
    id: 9,
    title: "The Red Fort",
    img: "https://kaldanhotels.com/images/kaldan/hotels-in-ecr-chennai.jpg",
    address:
      "Netaji Subhash Marg, Lal Qila, Chandni Chowk, New Delhi, Delhi 110006, India",
    latitude: 28.656159,
    longitude: 77.24102,
    type: "sightseeing",
    operating_hours: "9:30 AM - 4:30 PM (closed on Mondays)",
    price_for_two: "INR 70 for Indians, INR 900 for Foreigners",
    contact_info: {
      phone: "+91 11 1234 5678",
      email: "info@redfort.com",
      website: "http://www.redfort.com",
    },
  },
  {
    id: 10,
    title: "Dal Lake",
    img: "https://kaldanhotels.com/images/kaldan/hotels-in-ecr-chennai.jpg",
    address: "Boulevard Rd, Srinagar, Jammu and Kashmir 190001, India",
    latitude: 34.083658,
    longitude: 74.807182,
    type: "sightseeing",
    operating_hours: "24 hours",
    price_for_two: "Free",
    contact_info: {
      phone: "+91 194 1234 5678",
      email: "info@dallake.com",
      website: "http://www.dallake.com",
    },
  },

  {
    id: 11,
    title: "Wonderla Amusement Park",
    img: "https://kaldanhotels.com/images/kaldan/hotels-in-ecr-chennai.jpg",
    address: "28th Km, Mysore Road, Bengaluru, Karnataka 562109, India",
    latitude: 12.834365,
    longitude: 77.400621,
    type: "activity",
    operating_hours: "11:00 AM - 7:00 PM",
    price_for_two: "INR 2490",
    contact_info: {
      phone: "+91 80 2201 0333",
      email: "info.blr@wonderla.com",
      website: "https://www.wonderla.com/bangalore/",
    },
  },
  {
    id: 12,
    title: "Ramoji Film City",
    img: "https://kaldanhotels.com/images/kaldan/hotels-in-ecr-chennai.jpg",
    address: "Ramoji Film City Main Rd, Hyderabad, Telangana 501512, India",
    latitude: 17.254304,
    longitude: 78.680836,
    type: "activity",
    operating_hours: "9:00 AM - 5:30 PM",
    price_for_two: "INR 2450",
    contact_info: {
      phone: "+91 84 1500 3001",
      email: "info@ramojifilmcity.com",
      website: "https://www.ramojifilmcity.com/",
    },
  },
  {
    id: 13,
    title: "Kingdom of Dreams",
    img: "https://kaldanhotels.com/images/kaldan/hotels-in-ecr-chennai.jpg",
    address: "Sector 29, Gurugram, Haryana 122001, India",
    latitude: 28.467387,
    longitude: 77.072788,
    type: "activity",
    operating_hours: "12:30 PM - 12:00 AM",
    price_for_two: "Different categories available",
    contact_info: {
      phone: "+91 12 4454 8000",
      email: "info@kingdomofdreams.co.in",
      website: "http://www.kingdomofdreams.in/",
    },
  },
  {
    id: 14,
    title: "Della Adventure Park",
    img: "https://kaldanhotels.com/images/kaldan/hotels-in-ecr-chennai.jpg",
    address: "Kunegaon, Lonavala, Maharashtra 410401, India",
    latitude: 18.771664,
    longitude: 73.423539,
    type: "activity",
    operating_hours: "11:00 AM - 9:00 PM",
    price_for_two: "INR 2450",
    contact_info: {
      phone: "+91 21 1446 0080",
      email: "info@dellaadventure.com",
      website: "https://www.dellaadventure.com/",
    },
  },
  {
    id: 15,
    title: "Imagicaa",
    img: "https://kaldanhotels.com/images/kaldan/hotels-in-ecr-chennai.jpg",
    address:
      "30/31, Sangdewadi, Khopoli-Pali Road, Khalapur, Maharashtra 410203, India",
    latitude: 18.823358,
    longitude: 73.252274,
    type: "activity",
    operating_hours: "10:30 AM - 8:00 PM",
    price_for_two: "INR 2050",
    contact_info: {
      phone: "+91 22 4213 0405",
      email: "info@imagicaaworld.com",
      website: "https://www.imagicaaworld.com/",
    },
  },
  {
    id: 16,
    title: "Snow World",
    img: "https://kaldanhotels.com/images/kaldan/hotels-in-ecr-chennai.jpg",
    address:
      "Gate No.11, DLF Mall of India, Sector 18, Noida, Uttar Pradesh 201301, India",
    latitude: 28.567997,
    longitude: 77.320334,
    type: "activity",
    operating_hours: "11:00 AM - 9:00 PM",
    price_for_two: "INR 3450",
    contact_info: {
      phone: "+91 12 0450 0500",
      email: "info@snowworldindia.com",
      website: "https://snowworldindia.com/noida/",
    },
  },
  {
    id: 17,
    title: "Science City",
    img: "https://kaldanhotels.com/images/kaldan/hotels-in-ecr-chennai.jpg",
    address:
      "J.B.S Haldane Ave, Mirania Gardens, East Topsia, Topsia, Kolkata, West Bengal 700046, India",
    latitude: 22.539303,
    longitude: 88.402335,
    type: "activity",
    operating_hours: "9:00 AM - 8:00 PM",
    price_for_two: "INR 200",
    contact_info: {
      phone: "+91 33 2285 7878",
      email: "info@sciencecitykolkata.org.in",
      website: "https://sciencecitykolkata.org.in/",
    },
  },
  {
    id: 18,
    title: "Essel Worlds",
    img: "https://kaldanhotels.com/images/kaldan/hotels-in-ecr-chennai.jpg",
    address:
      "Global Pagoda Road, Gorai Island, Borivali West, Mumbai, Maharashtra 400091, India",
    latitude: 19.227027,
    longitude: 72.80635,
    type: "activity",
    operating_hours: "10:00 AM - 7:00 PM",
    price_for_two: "INR 5550",
    contact_info: {
      phone: "+91 22 6528 0305",
      email: "info@esselworld.in",
      website: "https://www.esselworld.in/",
    },
  },
  {
    id: 19,
    title: "Cubbon Park",
    img: "https://kaldanhotels.com/images/kaldan/hotels-in-ecr-chennai.jpg",
    address:
      "Kasturba Road, Behind High Court of Karnataka Ambedkar Veedhi, Sampangi Rama Nagar, Bengaluru, Karnataka 560001, India",
    latitude: 12.976347,
    longitude: 77.592928,
    type: "sightseeing",
    operating_hours: "24 hours",
    price_for_two: "INR 4450",
    contact_info: {
      phone: "+91 80 1234 5678",
      email: "info@cubbonpark.com",
      website: "https://www.cubbonpark.com/",
    },
  },
  {
    id: 20,
    title: "Chokhi Dhani",
    img: "https://kaldanhotels.com/images/kaldan/hotels-in-ecr-chennai.jpg",
    address: "12 Miles, Tonk Road, via Vatika, Jaipur, Rajasthan 303905, India",
    latitude: 26.78987,
    longitude: 75.836247,
    type: "activity",
    operating_hours: "5:00 PM - 11:00 PM",
    price_for_two: "INR 2450",
    contact_info: {
      phone: "+91 141 516 5000",
      email: "info@chokhidhani.com",
      website: "https://www.chokhidhani.com/",
    },
  },
  {
    id: 21,
    title: "Karim's",
    img: "https://imgs.search.brave.com/XPUcjc0MLeyVYtDdGlG77rfDgGAzHFey-NN9roNGBdw/rs:fit:1200:1200:1/g:ce/aHR0cDovL3d3dy5r/aWNoZW5jb2wuY29t/L3dwLWNvbnRlbnQv/dXBsb2Fkcy8yMDE4/LzExL2thcmltLmpw/Zw",
    address: "Jama Masjid, Gali Kababian, Old Delhi, Delhi 110006, India",
    type: "Food",
    latitude: 28.6505943,
    longitude: 77.2321288,
    operating_hours: "12:00 PM - 11:00 PM",
    price_for_two: "INR 2450",
    contact_info: {
      phone: "+91 11 2326 4981",
      email: "info@karimsrestaurant.com",
      website: "http://www.karimsrestaurant.com",
    },
  },
  {
    id: 22,
    title: "Bukhara",
    img: "https://imgs.search.brave.com/XPUcjc0MLeyVYtDdGlG77rfDgGAzHFey-NN9roNGBdw/rs:fit:1200:1200:1/g:ce/aHR0cDovL3d3dy5r/aWNoZW5jb2wuY29t/L3dwLWNvbnRlbnQv/dXBsb2Fkcy8yMDE4/LzExL2thcmltLmpw/Zw",
    address:
      "ITC Maurya, Diplomatic Enclave, Sardar Patel Marg, New Delhi, Delhi 110021, India",
    type: "Food",
    latitude: 28.596744,
    longitude: 77.173388,
    operating_hours: "12:30 PM - 2:45 PM, 7:00 PM - 11:45 PM",
    price_for_two: "INR 5450",
    contact_info: {
      phone: "+91 11 2611 2233",
      email: "info@itchotels.in",
      website:
        "https://www.itchotels.com/in/en/itcmaurya-new-delhi/dining/bukhara.html",
    },
  },
  {
    id: 23,
    title: "Leopold Cafe",
    img: "https://imgs.search.brave.com/hUyoZ8VANuPZr7-QOfgPnAz2hMBtsQeVpiGiALd0zpU/rs:fit:1200:1200:1/g:ce/aHR0cDovL3d3dy5r/aWNoZW5jb2wuY29t/L3dwLWNvbnRlbnQv/dXBsb2Fkcy8yMDE4/LzExL2thcmltLmpw/Zw",
    address: "Colaba Causeway, Mumbai, Maharashtra 400001, India",
    type: "Food",
    latitude: 18.9235793,
    longitude: 72.833168,
    operating_hours: "7:30 AM - 12:00 AM",
    price_for_two: "INR 1450",
    contact_info: {
      phone: "+91 22 2282 8185",
      email: "info@leopoldcafe.com",
      website: "http://www.leopoldcafe.com",
    },
  },
  {
    id: 24,
    title: "Indian Accent",
    img: "https://imgs.search.brave.com/_u6p7i5_19N0SzkbCqg-15_GNjRZNB9YEnllI9Z6cYg/rs:fit:1200:1200:1/g:ce/aHR0cDovL3d3dy5r/aWNoZW5jb2wuY29t/L3dwLWNvbnRlbnQv/dXBsb2Fkcy8yMDE4/LzExL2thcmltLmpw/Zw",
    address: "The Lodhi, Lodhi Road, New Delhi, Delhi 110003, India",
    type: "Food",
    latitude: 28.5938176,
    longitude: 77.2431154,
    operating_hours: "12:00 PM - 2:30 PM, 7:00 PM - 10:30 PM",
    price_for_two: "INR 2450",
    contact_info: {
      phone: "+91 11 6617 5151",
      email: "info@indianaccent.com",
      website: "https://www.indianaccent.com",
    },
  },
  {
    id: 25,
    title: "Peter Cat",
    img: "https://imgs.search.brave.com/Qr5PFSnOWsS3i_b0ayEgrzqLlsQDdW21ESaaQIECLc0/rs:fit:1200:1200:1/g:ce/aHR0cDovL3d3dy5r/aWNoZW5jb2wuY29t/L3dwLWNvbnRlbnQv/dXBsb2Fkcy8yMDE4/LzExL2thcmltLmpw/Zw",
    address: "18A, Park Street, Kolkata, West Bengal 700071, India",
    type: "Food",
    latitude: 22.5543993,
    longitude: 88.350233,
    operating_hours: "11:00 AM - 11:30 PM",
    price_for_two: "INR 2450",
    contact_info: {
      phone: "+91 33 2229 8841",
      email: "info@petercatrestaurant.com",
      website: "http://www.petercatrestaurant.com",
    },
  },
  {
    id: 26,
    title: "Tunday Kababi",
    img: "https://imgs.search.brave.com/_u6p7i5_19N0SzkbCqg-15_GNjRZNB9YEnllI9Z6cYg/rs:fit:1200:1200:1/g:ce/aHR0cDovL3d3dy5r/aWNoZW5jb2wuY29t/L3dwLWNvbnRlbnQv/dXBsb2Fkcy8yMDE4/LzExL2thcmltLmpw/Zw",
    address: "Aminabad, Lucknow, Uttar Pradesh 226018, India",
    type: "Food",
    latitude: 26.857246,
    longitude: 80.934132,
    operating_hours: "12:00 PM - 11:00 PM",
    price_for_two: "INR 1500",
    contact_info: {
      phone: "+91 522 2980600",
      email: "info@tundaykababi.com",
      website: "http://www.tundaykababi.com",
    },
  },
  {
    id: 27,
    title: "Britannia and Co.",
    img: "https://imgs.search.brave.com/7tL51Nu7z5L81w77nRYQACsknL6ys3nnT5wGvjqN5hs/rs:fit:1200:1200:1/g:ce/aHR0cDovL3d3dy5r/aWNoZW5jb2wuY29t/L3dwLWNvbnRlbnQv/dXBsb2Fkcy8yMDE4/LzExL2thcmltLmpw/Zw",
    address:
      "Wakefield House, 11 Sprott Road, Ballard Estate, Fort, Mumbai, Maharashtra 400001, India",
    type: "Food",
    latitude: 18.943577,
    longitude: 72.833882,
    operating_hours: "12:00 PM - 4:00 PM",
    price_for_two: "INR 1450",
    contact_info: {
      phone: "+91 22 2261 5264",
      email: "info@britanniarestaurant.com",
      website: "http://www.britanniarestaurant.com",
    },
  },
  {
    id: 28,
    title: "Saravana Bhavan",
    img: "https://imgs.search.brave.com/4YctK8I8vFjCtvPCbTSxeKlE9SdnV3abYPMy_KwqBhU/rs:fit:1200:1200:1/g:ce/aHR0cHM6Ly9tZWRp/YTIuaW5keWF0aW1n/YS5jb20vY29udGVu/dC9kdGltZy8yMDE5/L2ZlYi9kLzYvYmly/LWhvbmUtc2FyYXZh/bmEtaGhdZmV2LTQ1/LmpwZw",
    address:
      "Saravana Bhavan, Purasavakkam High Road, Kellys, Chennai, Tamil Nadu 600010, India",
    type: "Food",
    latitude: 13.08784,
    longitude: 80.2406,
    operating_hours: "8:00 AM - 11:00 PM",
    price_for_two: "INR 450",
    contact_info: {
      phone: "+91 44 2661 3311",
      email: "info@saravanabhavan.com",
      website: "https://www.saravanabhavan.com",
    },
  },
  {
    id: 29,
    title: "Dum Pukht",
    img: "https://imgs.search.brave.com/qzIQ2z2lA-lCE4QNZv6h4dxY5yEDkQeH11l0Bi47nbc/rs:fit:1200:1200:1/g:ce/aHR0cDovL3d3dy5r/aWNoZW5jb2wuY29t/L3dwLWNvbnRlbnQv/dXBsb2Fkcy8yMDE4/LzExL2thcmltLmpw/Zw",
    address:
      "ITC Maurya, Diplomatic Enclave, Sardar Patel Marg, New Delhi, Delhi 110021, India",
    type: "Food",
    latitude: 28.596744,
    longitude: 77.173388,
    operating_hours: "12:30 PM - 2:45 PM, 7:00 PM - 11:45 PM",
    price_for_two: "INR 5450",
    contact_info: {
      phone: "+91 11 2611 2233",
      email: "info@itchotels.in",
      website:
        "https://www.itchotels.com/in/en/itcmaurya-new-delhi/dining/dum-pukht.html",
    },
  },
  {
    id: 30,
    title: "Kesar Da Dhaba",
    img: "https://imgs.search.brave.com/PIvw8A5Zs3tK5yuxL53-LXmo8OXBqTKlh3-fW6m9lR0/rs:fit:1200:1200:1/g:ce/aHR0cDovL3d3dy5r/aWNoZW5jb2wuY29t/L3dwLWNvbnRlbnQv/dXBsb2Fkcy8yMDE4/LzExL2thcmltLmpw/Zw",
    address: "Chowk Passian, Near Town Hall, Amritsar, Punjab 143001, India",
    type: "Food",
    latitude: 31.628705,
    longitude: 74.875083,
    operating_hours: "12:00 PM - 11:00 PM",
    price_for_two: "INR 1000",
    contact_info: {
      phone: "+91 183 255 2103",
      email: "info@kesarrestaurant.com",
      website: "http://www.kesarrestaurant.com",
    },
  },
];

export const singlePostData = {
  id: 1,
  title: "Gateway of India",
  images: [
    "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2c/fb/c5/e2/caption.jpg?w=900&h=500&s=1",
    "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/2b/79/3a/gateway-of-india.jpg?w=900&h=500&s=1",
    "https://cdn.s3waas.gov.in/s311b921ef080f7736089c757404650e40/uploads/bfi_thumb/2018032370-olw6tnp2sowh5prd9ls5lwuo7dmk5yeqookn2h0ya2.jpg",
    "https://www.webpages.uidaho.edu/ngier/GatewayIndia.jpg",
  ],
  address: "Apollo Bandar, Colaba, Mumbai, Maharashtra 400001, India",
  latitude: 18.921984,
  longitude: 72.834654,
  type: "sightseeing",
  operating_hours: "24 hours",
  price_for_two: "Free",
  description:
    "If there is any landmark that the city of Mumbai can easily be identified with, it is unarguably the Gateway of India. This iconic waterfront monument dates back to the British Era, and ranks among the top places to visit in Mumbai. A must visit tourist attraction of your Mumbai Tour, the majestic gateway is famous for its grand and imposing appearance and the sweeping views of the Arabian Sea which it provides. You donot have to be an architecture fan to appreciate the Gateway of Mumbai. The salty breeze, the aroma of hot chai from the local tea-stall, and tourists eager to get a seating place by the sea add to the excitement of paying a visit to this tall arch.",
  contact_info: {
    phone: "+91 22 1234 5678",
    email: "info@gatewayofindia.com",
    website: "http://www.gatewayofindia.com",
  },
};

export const userData = {
  id: 1,
  name: "John Doe",
  img: "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
};
